"""
DOCUMENTATION — build the post-incident record.

Produces five sections for every incident:
  1. Timeline of lifecycle events with timestamps
  2. Root cause analysis narrative
  3. Impact assessment
  4. Resolution summary
  5. Preventive actions

The record is always written to SQLite (that is the authoritative copy). A
GitHub issue and a Slack message are optional delivery channels.

### Hard constraint

Sentinel **never modifies application code and never merges anything.** There
is no branch push, no pull request, no file write outside its own data
directory. Preventive actions that involve a code change are written as
*prose in the issue body* for a human to implement.

That boundary is deliberate and worth stating plainly: an agent authorised to
restart a Deployment has a bounded, reversible blast radius that recovery
validation can check. An agent authorised to change the code has an unbounded
one that no runtime check can verify. Those are different risk classes and
this project only takes the first.

The markdown is generated by string templating rather than by an LLM, so the
document is deterministic and reproducible from the incident record. The LLM
narrative, when present, is embedded as one clearly-labelled section.
"""
from __future__ import annotations

import logging

from app.models.incident import (
    Incident,
    RemediationAction,
    RootCause,
    ValidationOutcome,
    iso,
)

logger = logging.getLogger(__name__)

# Preventive actions per root cause. Prose, aimed at a human. Every entry that
# implies a code change says so explicitly, because Sentinel will not make it.
PREVENTIVE_ACTIONS: dict[RootCause, tuple[str, ...]] = {
    RootCause.CHAOS_DATABASE_FAULT: (
        "Confirm the chaos experiment was intentional. If it was, no action is "
        "needed beyond recording the result.",
        "If it was not intentional, rotate CHAOS_ADMIN_TOKEN and audit who can "
        "reach /api/chaos/fault.",
        "Consider gating CHAOS_MODE off in any environment that is not "
        "explicitly a game-day target.",
    ),
    RootCause.CHAOS_HTTP_FAULT: (
        "Confirm the chaos experiment was intentional.",
        "Note for future investigations: chaos-injected 503s are counted in "
        "http_requests_total but produce no access-log line, because the chaos "
        "middleware short-circuits before the access-log middleware. A dashboard "
        "panel documenting that would save the next responder some time.",
    ),
    RootCause.CHAOS_LATENCY_FAULT: (
        "Confirm the chaos experiment was intentional.",
        "Check whether the injected latency exceeded any client-side timeout; if "
        "it did, the resulting client errors are worth an alert of their own.",
    ),
    RootCause.CHAOS_NOTIFICATION_FAULT: (
        "Confirm the chaos experiment was intentional.",
        "Verify that citizen-service degrades gracefully when notification "
        "delivery fails, rather than failing the user's request.",
    ),
    RootCause.BAD_DEPLOYMENT: (
        "Review what changed in the rolled-back revision. Sentinel does not read "
        "or modify application code, so this is a human task.",
        "Add or strengthen a pre-deploy check that would have caught this "
        "(a smoke test against /readyz post-rollout is the cheapest option).",
        "Consider a canary or a longer rollout pause so a bad revision affects "
        "fewer requests before it is caught.",
    ),
    RootCause.MEMORY_LEAK: (
        "A restart reclaims the memory but does not fix the leak; it will recur. "
        "Profile the process to find the retained objects. This is a code change "
        "and Sentinel will not make it.",
        "Set a container memory limit so the kubelet OOM-kills and restarts the "
        "pod automatically before the node comes under pressure.",
        "Because there is no cAdvisor or kube-state-metrics in this cluster, RSS "
        "from prometheus_client is the only memory signal. Adding one of those "
        "would make container-level memory alerting possible.",
    ),
    RootCause.CPU_SATURATION: (
        "Determine whether this is genuine load growth or a hot loop. Without "
        "cAdvisor, CPU cannot be compared against the container limit, so "
        "throttling is currently invisible.",
        "Review whether the replica band (MIN_REPLICAS/MAX_REPLICAS) is still "
        "appropriate for the traffic level.",
    ),
    RootCause.CAPACITY_SHORTFALL: (
        "Right-size the Deployment's baseline replica count rather than relying "
        "on reactive scaling.",
        "This is single-node K3s: replicas beyond what the node can schedule "
        "will sit Pending. Consider whether the node needs to be larger.",
    ),
    RootCause.POD_CRASH_LOOP: (
        "A crash loop with no recent deployment usually means a config or "
        "dependency problem, not a code regression. Check ConfigMaps, Secrets "
        "and the database connection.",
        "Review the container's startupProbe/readinessProbe timings — an "
        "aggressive probe can manufacture a crash loop on a slow start.",
    ),
    RootCause.SERVICE_DOWN: (
        "Determine why the pods stopped being scrapeable. Check node pressure "
        "and eviction events; this is a single-node cluster, so node-level "
        "problems present as service-level ones.",
    ),
    RootCause.DOWNSTREAM_DEPENDENCY: (
        "Add an alert on the downstream service itself. Sentinel can only "
        "remediate a service it has an alert and a target for.",
        "Verify the caller's timeout and fallback behaviour. /readyz returning "
        "HTTP 200 with status=degraded means a status-code-only health check "
        "will not notice this at all.",
    ),
    RootCause.DATABASE_FAILURE: (
        "Databases are explicitly non-remediable by Sentinel. Investigate "
        "Postgres directly: connections, disk, WAL.",
        "Check the PVC's free space — a full volume presents as a connection "
        "failure.",
    ),
    RootCause.UNKNOWN: (
        "Sentinel could not attribute this incident. Review the evidence bundle "
        "below and, if a pattern emerges, add a rule to "
        "sentinel-ai/app/lifecycle/rca.py so the next occurrence is handled.",
    ),
}


def build_document(incident: Incident) -> dict[str, str]:
    """Render the five sections. Returns a dict of markdown strings."""
    return {
        "timeline": _timeline(incident),
        "root_cause_analysis": _rca_section(incident),
        "impact": _impact(incident),
        "resolution": _resolution(incident),
        "prevention": _prevention(incident),
    }


def render_markdown(incident: Incident) -> str:
    """Full markdown document, suitable for a GitHub issue body."""
    sections = build_document(incident)
    status_line = (
        f"**Status:** {incident.status.value}"
        + (f" (escalated: {incident.escalation_reason.value})" if incident.escalated else "")
    )
    return "\n".join(
        [
            f"# {incident.id} — {incident.alertname}",
            "",
            f"**Severity:** {incident.severity.value}  ",
            f"**Service:** {incident.app or 'unknown'} in `{incident.namespace}`  ",
            f"**Opened:** {iso(incident.created_at)}  ",
            f"**Last update:** {iso(incident.updated_at)}  ",
            status_line,
            f"**Alert firings folded into this incident:** {incident.firing_count}",
            "",
            "## Root cause analysis",
            sections["root_cause_analysis"],
            "",
            "## Impact",
            sections["impact"],
            "",
            "## Resolution",
            sections["resolution"],
            "",
            "## Timeline",
            sections["timeline"],
            "",
            "## Preventive actions",
            sections["prevention"],
            "",
            "---",
            "_Generated by Sentinel, the autonomous SRE agent. Sentinel executes "
            "only four bounded Kubernetes actions (rollout restart, rollback, "
            "scale within a band, chaos-fault reset) and **never modifies "
            "application code, opens a pull request, or merges anything**. Any "
            "code change suggested above is a proposal for a human._",
        ]
    )


def _timeline(incident: Incident) -> str:
    if not incident.timeline:
        return "_no timeline events recorded_"
    lines = ["| Time (UTC) | Phase | Event |", "| --- | --- | --- |"]
    for event in incident.timeline:
        # Pipes in a message would break the table.
        message = event.message.replace("|", "\\|").replace("\n", " ")
        lines.append(f"| {iso(event.at)} | `{event.phase.value}` | {message} |")
    return "\n".join(lines)


def _rca_section(incident: Incident) -> str:
    h = incident.hypothesis
    if h is None:
        return "_no hypothesis was formed_"
    parts = [
        f"**Root cause:** `{h.root_cause.value}`  ",
        f"**Confidence:** {h.confidence:.2f}"
        + (
            f" (rule engine: {h.rule_confidence:.2f})"
            if h.rule_confidence is not None
            else ""
        )
        + "  ",
        f"**Analysis source:** {h.source}",
        "",
        h.reasoning,
    ]
    if h.llm_note:
        parts += [
            "",
            "### Note on LLM involvement",
            h.llm_note,
            "",
            "_The LLM's role is bounded by design: it may improve the narrative "
            "and nudge confidence within a small clamped range, but it cannot "
            "choose the remediation action, cannot propose a root cause outside "
            "the fixed enum, and has no access to a shell, to kubectl, or to the "
            "Kubernetes API._",
        ]
    if h.supporting:
        parts += ["", "### Supporting evidence"]
        parts += [f"- {s}" for s in h.supporting[:25]]
    evidence = incident.evidence
    if evidence and evidence.errors:
        parts += [
            "",
            "### Gaps in the evidence",
            "_These collectors failed, so the analysis was made without them:_",
        ]
        parts += [f"- {e}" for e in evidence.errors]
    return "\n".join(parts)


def _impact(incident: Incident) -> str:
    evidence = incident.evidence
    if evidence is None:
        return "_no evidence bundle available_"

    duration_seconds = (incident.resolved_at or incident.updated_at) - incident.created_at
    lines = [
        f"- **Duration under Sentinel's management:** {duration_seconds / 60:.1f} minutes "
        "(from alert receipt, not from the true onset — Alertmanager's `for:` "
        "duration means the problem started earlier)",
        f"- **Affected service:** {incident.app or 'unknown'}",
    ]
    if evidence.error_rate is not None:
        lines.append(f"- **5xx error rate at investigation:** {evidence.error_rate:.2%}")
    if evidence.error_rate_5xx_count is not None:
        lines.append(
            f"- **Approximate failed requests in the window:** "
            f"{evidence.error_rate_5xx_count:.0f}"
        )
    if evidence.p95_latency_seconds is not None:
        lines.append(f"- **p95 latency:** {evidence.p95_latency_seconds:.2f}s")
    if evidence.request_rate is not None:
        lines.append(f"- **Request rate:** {evidence.request_rate:.2f} req/s")
    if evidence.notification_deliveries:
        sent = evidence.notification_deliveries.get("Sent", 0.0)
        failed = evidence.notification_deliveries.get("Failed", 0.0)
        lines.append(
            f"- **Notification deliveries in the window:** {sent:.0f} Sent / "
            f"{failed:.0f} Failed"
        )
    if evidence.restart_count_total:
        lines.append(f"- **Container restarts observed:** {evidence.restart_count_total}")
    if evidence.health_status:
        lines.append(f"- **/readyz reported:** `{evidence.health_status}`")

    lines.append(
        "- **User-facing impact:** inferred from HTTP metrics only. There is no "
        "real user-session telemetry in this stack, so this is an approximation."
    )
    return "\n".join(lines)


def _resolution(incident: Incident) -> str:
    if not incident.attempts:
        return (
            "No remediation was attempted. "
            + (incident.escalation_detail or "See the timeline for why.")
        )

    lines: list[str] = []
    for index, attempt in enumerate(incident.attempts, start=1):
        lines.append(f"### Attempt {index}: `{attempt.plan.action.value}`")
        lines.append(f"- Confidence: {attempt.plan.confidence:.2f}")
        lines.append(f"- Rationale: {attempt.plan.rationale}")
        if attempt.verdict:
            verdict = "ALLOWED" if attempt.verdict.allowed else "DENIED"
            lines.append(f"- Policy: **{verdict}** — {attempt.verdict.detail}")
        if attempt.result:
            outcome = "succeeded" if attempt.result.succeeded else "FAILED"
            dry = " (DRY_RUN, nothing was applied)" if attempt.result.dry_run else ""
            lines.append(
                f"- Execution: {outcome}{dry} in "
                f"{attempt.result.duration_seconds:.2f}s — {attempt.result.detail}"
            )
        if attempt.validation:
            lines.append(
                f"- Recovery validation: **{attempt.validation.outcome.value}** "
                f"after {attempt.validation.elapsed_seconds:.0f}s — "
                f"{attempt.validation.detail}"
            )
            if attempt.validation.skipped_checks:
                lines.append(
                    "- Checks skipped: " + "; ".join(attempt.validation.skipped_checks)
                )
        lines.append("")

    if incident.escalated:
        lines.append(
            f"**Escalated to a human.** Reason: "
            f"`{incident.escalation_reason.value if incident.escalation_reason else 'unknown'}`. "
            f"{incident.escalation_detail}"
        )
    elif incident.status.value == "resolved":
        last = incident.attempts[-1]
        degraded = (
            last.validation is not None
            and last.validation.outcome is ValidationOutcome.DEGRADED
        )
        if degraded:
            lines.append(
                "**Resolved with a caveat.** The target service recovered but "
                "/readyz still reports `degraded`, meaning a downstream "
                "dependency remains unreachable. A separate incident on that "
                "dependency is warranted."
            )
        else:
            lines.append(
                "**Resolved autonomously.** Recovery validation passed, so the "
                "incident is closed without human involvement."
            )
    return "\n".join(lines)


def _prevention(incident: Incident) -> str:
    root_cause = (
        incident.hypothesis.root_cause if incident.hypothesis else RootCause.UNKNOWN
    )
    actions = list(PREVENTIVE_ACTIONS.get(root_cause, PREVENTIVE_ACTIONS[RootCause.UNKNOWN]))

    # Situational additions that depend on how the incident actually went,
    # not just on the root cause.
    executed = [a for a in incident.attempts if a.result is not None]
    if len(executed) > 1:
        actions.append(
            f"Sentinel needed {len(executed)} actions to resolve this. If that "
            "pattern repeats for this root cause, the first candidate in "
            "`ACTION_LADDER` (app/lifecycle/decision.py) is probably wrong."
        )
    denied = [a for a in incident.attempts if a.verdict and not a.verdict.allowed]
    if denied:
        reasons = {a.verdict.reason.value for a in denied if a.verdict.reason}
        actions.append(
            "The Policy Engine denied "
            f"{len(denied)} candidate action(s) ({', '.join(sorted(reasons))}). If a "
            "denial was wrong, change the threshold or allow-list in config — do "
            "not weaken the check itself."
        )
    if incident.hypothesis and not incident.hypothesis.llm_used:
        actions.append(
            "This analysis was entirely rule-based (no OPENAI_API_KEY configured, "
            "or the LLM's answer was rejected). That is a supported mode and "
            "changes nothing about what Sentinel was permitted to do."
        )
    if any(
        a.plan.action is RemediationAction.RESTART_DEPLOYMENT
        and a.result
        and a.result.succeeded
        for a in incident.attempts
    ):
        actions.append(
            "A rollout restart resolved this. A restart clears symptoms without "
            "explaining them — if the same alert recurs, treat the restart as a "
            "workaround and find the cause."
        )

    return "\n".join(f"- {a}" for a in actions)


def issue_title(incident: Incident) -> str:
    root_cause = (
        incident.hypothesis.root_cause.value if incident.hypothesis else "unknown"
    )
    prefix = "[ESCALATED]" if incident.escalated else "[RESOLVED]"
    return f"{prefix} {incident.id}: {incident.alertname} on {incident.app or '?'} ({root_cause})"


def slack_summary(incident: Incident) -> str:
    """Short mrkdwn summary. Slack is a notification sink, not the record."""
    h = incident.hypothesis
    icon = ":rotating_light:" if incident.escalated else ":white_check_mark:"
    action_line = "no action taken"
    executed = [a for a in incident.attempts if a.result is not None]
    if executed:
        action_line = ", ".join(
            f"{a.plan.action.value}"
            + ("(dry-run)" if a.result and a.result.dry_run else "")
            for a in executed
        )
    lines = [
        f"{icon} *{incident.id}* — `{incident.alertname}` on *{incident.app or 'unknown'}*",
        f"• Status: *{incident.status.value}*",
        f"• Root cause: `{h.root_cause.value if h else 'unknown'}`"
        + (f" (confidence {h.confidence:.2f})" if h else ""),
        f"• Actions: {action_line}",
    ]
    if incident.escalated:
        lines.append(
            f"• *Escalated:* {incident.escalation_reason.value if incident.escalation_reason else '?'}"
            f" — {incident.escalation_detail[:300]}"
        )
    if incident.attempts and incident.attempts[-1].validation:
        lines.append(
            f"• Validation: *{incident.attempts[-1].validation.outcome.value}*"
        )
    return "\n".join(lines)
